Django--GoogleMapsApi-main/google/urls.py
from .views import *
from django.urls import path, include
from google import views as view
'La página define las rutas y direcciones URL del proyecto. Cada ruta especifica una URL y la función de vista asociada que se ejecutará cuando se acceda a esa URL en el navegador.'
urlpatterns = [
   path('', view.vistaBase, name='inicio'),
   path('registro/', view.registro, name='registro'),
   path('login/', view.login, name='login'),
   path('logout/', view.logout_view, name='logout'),
   path('home',view.home, name="home"),
   path('geocode',view.geocode, name="geocode"),
   path('geocode/club/<int:pk>',view.geocode_club, name="geocode_club"),
   path('mapa/',view.mapa, name="map"),
   path('mydata',view.mydata, name="mydata"),
   path('crearEmpresa', view.crearEmpresa, name='crearEmpresa'),
   path('editarEmpresa/<NIT>', view.editarEmpresa, name='editarEmpresa'),
   path('inactivarEmpresa/<NIT>', view.inactivarEmpresa, name='inactivarEmpresa'),
  # path('crearSede', view.crearSede, name='crearSede'),
   path('listaEmp/<str:rest>/', view.vistaListaEmpl, name='listaEmp'),
   path('crearEmp/<str:rest>/', view.vistaCrearEmpl, name='crearEmp'),
   path('editarEmp/<str:rest>/<str:ced>/', view.vistaEditarEmpl, name='editarEmp'),
   path('verEmp/<str:rest>/<str:ced>/', view.vistaVerEmpl, name='verEmp'),
   path('estadoEmp/<str:rest>/<str:ced>/', view.estadoEmp, name='estadoEmp'),
]

Django--GoogleMapsApi-main/googleApp/urls.py
from .views import *
from django.urls import path, include
from googleApp import views as view
'La página define las rutas y direcciones URL del proyecto. Cada ruta especifica una URL y la función de vista asociada que se ejecutará cuando se acceda a esa URL en el navegador.'
urlpatterns = [
   path('', view.vistaBase, name='inicio'),
   path('registro/', view.registro, name='registro'),
   path('login/', view.login, name='login'),
   path('logout/', view.logout_view, name='logout'),
   path('home',view.home, name="home"),
   path('geocode',view.geocode, name="geocode"),
   path('geocode/club/<int:pk>',view.geocode_club, name="geocode_club"),
   path('geocode_sede/club/<str:pk>', view.geocode_club_sede, name="geocode_club_sede"),
   path('mapa/',view.mapa, name="map"),
   path('mapa_sede/', view.mapa_sede, name="map_sede"),
   path('mydata',view.mydata, name="mydata"),
   path('obtener_Ser_Esp/',view.obtener_Ser_Esp, name="obtener_Ser_Esp"),
   path('crearEmpresa', view.crearEmpresa, name='crearEmpresa'),
   path('editarEmpresa/<NIT>', view.editarEmpresa, name='editarEmpresa'),
   path('inactivarEmpresa/<NIT>', view.inactivarEmpresa, name='inactivarEmpresa'),
   path('crearSede/<str:rest>', view.crearSede, name='crearSede'),
   path('editarSede/<nombre>', view.editarSede, name='editarSede'),
   path('inactivarSede/<nombre>', view.inactivarSede, name='inactivarSede'),
   path('listaEmp/<str:rest>/', view.vistaListaEmpl, name='listaEmp'),
   path('crearEmp/<str:rest>/', view.vistaCrearEmpl, name='crearEmp'),
   path('editarEmp/<str:rest>/<str:ced>/', view.vistaEditarEmpl, name='editarEmp'),
   path('verEmp/<str:rest>/<str:ced>/', view.vistaVerEmpl, name='verEmp'),
   path('estadoEmp/<str:rest>/<str:ced>/', view.estadoEmp, name='estadoEmp'),
   path('mydataBusqueda',view.mydataBusqueda, name="mydataBusqueda"),
   path('servicios-especialidades/', view.servicios_especialidades, name='servicios_especialidades'),
   path('crear-servicio/', view.crearServicio, name='crear_servicio'),
   path('editar-servicio/<str:servicio_id>', view.editarServicio, name='editar_servicio'),
   path('eliminar-servicio/<str:servicio_id>', view.eliminarServicio, name='eliminar_servicio'),
   path('especialidades/', view.especialidades, name='especialidades'),
   path('crear-especialidades/', view.crearEspecialidad, name='crear_especialidades'),
   path('editar-especialidad/<str:servicio_id>', view.editarEspecialidad, name='editar_especialidad'),
   path('eliminar-especialidad/<str:servicio_id>', view.eliminarEspecialidad, name='eliminar_especialidad'),
   path('listaEmp/', view.vistaListaEmplTodos, name='vistaListaEmplTodos'),
   path('mapaEmp/<str:rest>',view.mapaEmp, name="mapaEmp"),
]

Django--GoogleMapsApi-main/google_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('googleApp.urls')),
]

Django--GoogleMapsApi-main/googleApp/models.py
from djongo import models
from django.db import models as model
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.

'''El modelo Ciudades representa una ciudad con dos campos: _id y nombre. El campo _id es un campo de identificación único y nombre es el nombre de la ciudad.'''
class Ciudades(models.Model):
    _id = models.ObjectIdField(primary_key=True)
    nombre = models.CharField(max_length=100)

    class Meta:
        db_table = 'Ciudades'

    def __str__(self):
        return self.nombre

'''El modelo Servicios representa un servicio con dos campos: _id y nombre. El campo _id es un campo de identificación único y nombre es el nombre del servicio.'''
class Servicios(models.Model):
    _id = models.ObjectIdField(primary_key=True)
    nombre = models.CharField(max_length=100)

    class Meta:
        db_table = 'Servicios'

    def __str__(self):
        return self.nombre

'''El modelo Especialidades representa una especialidad con dos campos: _id y nombre. El campo _id es un campo de identificación único y nombre es el nombre de la especialidad.'''
class Especialidades(models.Model):
    _id = models.ObjectIdField(primary_key=True)
    nombre = models.CharField(max_length=100)

    class Meta:
        db_table = 'Especialidades'

    def __str__(self):
        return self.nombre


'''El modelo Empresas representa una empresa con varios campos, como NIT (número de identificación tributaria), 
nombre, descripcion, telefono, ciudad (que es una clave foránea que se relaciona con el modelo Ciudades), 
fechaFundacion, email, mision, vision, paginaWeb, estado, direccion, latitude y longitude (para la ubicación geográfica de la empresa en la api de google).'''
class Empresas(models.Model):
    NIT = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=500)
    telefono = models.CharField(max_length=100)
    ciudad = models.ForeignKey(Ciudades, on_delete=models.CASCADE)
    fechaFundacion = models.DateField()
    email = models.CharField(max_length=100)
    mision = models.TextField()
    vision = models.TextField()
    paginaWeb = models.CharField(max_length=500)
    estado = models.BooleanField(default=True)
    direccion = models.CharField(max_length=500)
    latitude = models.FloatField()
    longitude = models.FloatField()
    especialidades = models.ManyToManyField(Especialidades, related_name='Empresas')
    servicios = models.ManyToManyField(Servicios, related_name='Empresas')

    class Meta:
        db_table = 'Empresas'

    def __str__(self):
        return str(self.latitude) + str(self.longitude)

class Sedes(models.Model):
   _id = models.ObjectIdField(primary_key=True)
   nombre = models.CharField(max_length=100, unique=True)
   telefono = models.CharField(max_length=100)
   direccion = models.CharField(max_length=100)
   empresa = models.ForeignKey(Empresas, on_delete=models.CASCADE)
   ciudad = models.ForeignKey(Ciudades, on_delete=models.CASCADE)
   estado = models.BooleanField(default=True)
   latitude = models.FloatField()
   longitude = models.FloatField()

   class Meta:
       db_table = 'Sedes'

   def __str__(self):
       return str(self.latitude) + str(self.longitude)


'''El modelo Empleados representa un empleado de una empresa con campos como
 nombres, apellidos, experienciaCargo, tipoDoc, documento, cargo, estado, fechaNacimiento, experiencia,
 videoEntrevista, telefono, imagen, entrevista, permiso, email y empresa (que es una clave foránea que se relaciona con el modelo Empresas).'''
class Empleados(models.Model):
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    experienciaCargo = models.CharField(max_length=100,default='1')
    tipoDoc = models.CharField(max_length=100)
    documento = models.CharField(max_length=100)
    cargo = models.CharField(max_length=100)
    estado = models.CharField(max_length=100)
    fechaNacimiento = models.DateField()
    experiencia = models.IntegerField(default=0)
    videoEntrevista = models.CharField(max_length=100)
    telefono = models.CharField(max_length=100)
    imagen = models.TextField(default="n")
    entrevista = models.TextField(default="n")
    permiso = models.TextField(default="n")
    email = models.EmailField()
    empresa = models.ForeignKey(Empresas, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Empleados'

    def __str__(self):
        return self.nombres

'''El modelo CustomUserManager es un administrador personalizado para el modelo de usuario personalizado
. Define métodos para crear usuarios y superusuarios.'''
class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, contraseña, **extra_fields):
        if not email:
            raise ValueError('El correo electronico debe ser ingresado')
        if not username:
            raise ValueError('El nombre de usuario debe ser ingresado')

        user = self.model(
            username=username,
            email=self.normalize_email(email),
            rol='Cliente',
            contraseña=contraseña,
        )
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, contraseña, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        user = self.create_user(
            username=username,
            email=email,
            contraseña=contraseña,
        )
        user.rol = 'Administrador'
        user.is_superuser = True
        user.save(using=self._db)
        return user


'''El modelo Usuarios es una implementación personalizada del modelo de usuario proporcionado por Django llamado AbstractBaseUser. Este modelo de usuario personalizado se utiliza para autenticación y gestión de usuarios en el sitio. Tiene campos como _id, username, contraseña, email y rol. El campo USERNAME_FIELD se establece en 'email' para autenticar a los usuarios utilizando su correo electrónico. 
También se define un administrador personalizado (CustomUserManager) para este modelo de usuario.
Además, el modelo Usuarios tiene métodos adicionales para verificar los permisos del usuario y para comprobar si el usuario es un administrador o un cliente.
'''
class Usuarios(AbstractBaseUser):
    _id = models.ObjectIdField(primary_key=True)
    username = models.CharField(max_length=30, unique=True)
    contraseña = models.CharField(max_length=128)
    email = models.EmailField(unique=True)
    rol = models.CharField(max_length=20)
    USERNAME_FIELD = 'email'
    PASSWORD_FIELD = 'contraseña'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()
    password = None

    class Meta:
        db_table = 'Usuarios'

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_admin(self):
        return self.rol == 'Administrador'

    @property
    def is_cliente(self):
        return self.rol == 'Cliente'

    def check_password(self, raw_password):
        if raw_password == self.contraseña:
            return True
        return False

Django--GoogleMapsApi-main/googleApp/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

mode_of_transport = [
    ("Driving", "driving"),
    ("Bicycling", "bicycling"),
    ("Walking", "walking"),
    ("Transit", "transit"),
]


class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'


class empresaForm(forms.ModelForm):
    class Meta:
        model = Empresas
        fields = ('NIT', 'nombre', 'mision', 'vision', 'descripcion', 'telefono', 'direccion', 'email', 'paginaWeb')
        widgets = {
            'NIT': forms.NumberInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'nombre': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'mision': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 5,  # número de filas del textarea
                    'cols': 40  # número de columnas del textarea
                }
            ),
            'vision': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 5,  # número de filas del textarea
                    'cols': 40  # número de columnas del textarea
                }
            ),
            'descripcion': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 5,  # número de filas del textarea
                    'cols': 40  # número de columnas del textarea
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'telefono': forms.NumberInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'direccion': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'paginaWeb': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            )
        }


class serviciosForm(forms.ModelForm):
    class Meta:
        model = Servicios
        fields = ['nombre']
        widgets = {
            'nombre': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }

class especialidadesForm(forms.ModelForm):
    class Meta:
        model = Especialidades
        fields = ['nombre']
        widgets = {
            'nombre': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }



class sedeForm(forms.ModelForm):
    class Meta:
        model = Sedes
        fields = ('nombre', 'telefono', 'direccion')
        widgets = {
            'nombre': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'telefono': forms.NumberInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'direccion': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }


class empleadoForm(forms.ModelForm):
    class Meta:
        model = Empleados
        fields = ('nombres', 'apellidos', 'telefono', 'email',
                  'documento', 'cargo', 'experiencia', 'experienciaCargo')
        widgets = {
            'nombres': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'documento': forms.TextInput(attrs={'class': 'form-control'}),
            'cargo': forms.TextInput(attrs={'class': 'form-control'}),
            'experiencia': forms.TextInput(attrs={'class': 'form-control'}),
            'experienciaCargo': forms.TextInput(attrs={'class': 'form-control'}),
        }

Django--GoogleMapsApi-main/googleApp/templates/Empresas/create.html
{% extends 'google/base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">

  <link rel="stylesheet" type="text/css" href="{% static 'css/estiloCrear.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/fontello.css' %}">

  <div style="display:flex; flex-direction:column; align-items:center;">
    <div class="card" style="width:90%;">
        <div class="card-body">
            <div class="text-center">
                <a class="icon-cancel" title="Cerrar" id="sidebar-close" href="{% url 'map' %}"></a>
                <h2>Crear Empresa</h2>
            </div>
            <form method="POST" class="form_2_cols">
                {% csrf_token %}
                <div style="display:flex; justify-content:space-between;" class="row">

                        <div class="col-md-6">
                        {{ form.as_p }}
                        </div>


                        <div class="col-md-6">

                            <div class="form-group">
                                <label>Ubicación de la empresa*</label>
                                <select name="ciudad" id="ciudad" class="form-control">
                                    {% for ciudad in ciudades %}
                                    <option value="{{ ciudad.nombre }}">{{ ciudad.nombre }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Fecha de Fundación*</label>
                                <input type="date" class="form-control" id="fechaFundacion" name="fechaFundacion"
                                       max="{% now 'Y-m-d' %}" required>
                            </div>

                            <div class="form-group">
                                <label for="id_especialidades">Especialidades:</label>
                                <select name="especialidades" id="id_especialidades" class="select2 form-control" multiple required>
                                  {% for especialidad in especialidades %}
                                    <option value="{{ especialidad.pk }}">{{ especialidad.nombre }}</option>
                                  {% endfor %}
                                </select>
                              </div>

                              <div class="form-group">
                                <label for="id_servicios">Servicios:</label>
                                <select name="servicios" id="id_servicios" class="form-control select2" multiple required>
                                  {% for servicio in servicios %}
                                    <option value="{{ servicio.pk }}">{{ servicio.nombre }}</option>
                                  {% endfor %}
                                </select>
                              </div>

                        </div>
                    </div>






                <button class="btn btn-default">
                    Enviar
                </button>
            </form>
        </div>
    </div>
  </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
$(document).ready(function() {
  $('.select2').select2();
});
</script>
{% endblock %}

Django--GoogleMapsApi-main/googleApp/templates/Empresas/edit.html
{% extends 'google/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/estiloEditar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/fontello.css' %}">

<div class="container col-md-7" style="padding-top: 20px; padding-bottom: 20px;">
    <div style="display:flex; flex-direction:column; align-items:center;">
        <div class="card">
            <div class="card-body">
                <div class="text-center">
                    <a class="icon-cancel" title="Cerrar" id="sidebar-close" href="{% url 'map' %}"></a>
                    <h2>Editar Empresa</h2>
                </div>

                <form method="POST">
                    {% csrf_token %}

                    {{ form.as_p }}
                    <div class="form-group">
                        <label>Ubicación de la empresa</label>
                        <select name="ciudad" id="ciudad" class="form-control">
                            {% for ciudad in ciudades %}
                            <option value="{{ ciudad.nombre }}" {% if empresa.ciudad.nombre == ciudad.nombre %} selected {% endif %}>{{ ciudad.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Fecha de Fundación</label>
                        <input type="date" class="form-control" id="fechaFundacion" name="fechaFundacion" max="{% now 'Y-m-d' %}" value="{{ empresa.fechaFundacion|date:"Y-m-d" }}">
                    </div>

                    <!-- Campos de Especialidades -->
                    <div class="form-group">
                        <label for="id_especialidades">Especialidades:</label>
                        <select name="especialidades" id="id_especialidades" class="select2 form-control" multiple required>
                            {% for especialidad in especialidades %}
                            <option value="{{ especialidad.pk }}" {% if especialidad in empresa.especialidades.all %} selected {% endif %}>{{ especialidad.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <!-- Campos de Servicios -->
                    <div class="form-group">
                        <label for="id_servicios">Servicios:</label>
                        <select name="servicios" id="id_servicios" class="select2 form-control" multiple required>
                            {% for servicio in servicios %}
                            <option value="{{ servicio.pk }}" {% if servicio in empresa.servicios.all %} selected {% endif %}>{{ servicio.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <button class="btn">
                        Guardar Cambios
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% load static %}
<script type="text/javascript" src="{% static 'javascript/sidebar.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
$(document).ready(function() {
  $('.select2').select2();
});
</script>
{% endblock %}